# Generated by Django 5.0.3 on 2024-04-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
